<?php
	class Germany {

		var $provinces;

		function __construct(){
		    $this->setProvinces();
		}

		function setProvinces(){
      /* INSERT */
  		$provinces = array(
        'Aalen',
        'Ahlen',
        'Amburgo',
        'Aquisgrana',
        'Arnsberg',
        'Aschaffenburg',
        'Augusta',
        'Bad Homburg vor der Höhe',
        'Bad Salzuflen',
        'Baden-Baden',
        'Bayreuth',
        'Bamberga',
        'Bergheim (Renania Settentrionale-Vestfalia)',
        'Bergisch Gladbach',
        'Berlino',
        'Bielefeld',
        'Bocholt',
        'Bochum',
        'Bonn',
        'Bottrop',
        'Brandeburgo sulla Havel',
        'Braunschweig',
        'Brema',
        'Bremerhaven',
        'Castrop-Rauxel',
        'Celle',
        'Chemnitz',
        'Coblenza',
        'Colonia',
        'Costanza',
        'Cottbus',
        'Darmstadt',
        'Delmenhorst',
        'Dessau-Roßlau',
        'Detmold',
        'Dinslaken',
        'Dormagen',
        'Dorsten',
        'Dortmund',
        'Dresda',
        'Duisburg',
        'Düren',
        'Düsseldorf',
        'Erfurt',
        'Erlangen',
        'Eschweiler',
        'Essen',
        'Esslingen am Neckar',
        'Euskirchen',
        'Flensburgo',
        'Francoforte sul Meno',
        'Francoforte sull\'Oder',
        'Frechen',
        'Friburgo in Brisgovia',
        'Friedrichshafen',
        'Fulda',
        'Fürth (Baviera)',
        'Garbsen',
        'Gelsenkirchen',
        'Gera',
        'Gießen',
        'Gladbeck',
        'Goslar',
        'Göppingen',
        'Görlitz',
        'Gottinga',
        'Greifswald',
        'Grevenbroich',
        'Gütersloh',
        'Hagen',
        'Halle (Saale)',
        'Hameln',
        'Hamm',
        'Hanau',
        'Hannover',
        'Hattingen',
        'Herford',
        'Heidelberg',
        'Heilbronn',
        'Herne',
        'Herten',
        'Hilden',
        'Hildesheim',
        'Hürth',
        'Ibbenbüren',
        'Ingolstadt',
        'Iserlohn',
        'Jena',
        'Kaiserslautern',
        'Karlsruhe',
        'Kassel',
        'Kempten (Allgäu)',
        'Kerpen',
        'Kiel',
        'Krefeld',
        'Landshut',
        'Langenfeld (Rheinland)',
        'Langenhagen',
        'Leverkusen',
        'Lingen (Ems)',
        'Lippstadt',
        'Lipsia',
        'Lubecca',
        'Lüdenscheid',
        'Ludwigsburg',
        'Ludwigshafen am Rhein',
        'Lünen',
        'Luneburgo',
        'Magdeburgo',
        'Magonza',
        'Mannheim',
        'Marburgo',
        'Marl',
        'Meerbusch',
        'Menden (Sauerland)',
        'Minden',
        'Moers',
        'Monaco',
        'Mönchengladbach',
        'Mülheim an der Ruhr',
        'Münster',
        'Neubrandenburg',
        'Neumünster',
        'Neuss',
        'Neustadt an der Weinstraße',
        'Neuwied',
        'Norderstedt',
        'Nordhorn',
        'Norimberga',
        'Nuova Ulma',
        'Oberhausen',
        'Offenbach am Main',
        'Offenburg',
        'Oldenburg',
        'Osnabrück',
        'Paderborn',
        'Pforzheim',
        'Plauen',
        'Pulheim',
        'Potsdam',
        'Ratingen',
        'Ratisbona',
        'Recklinghausen',
        'Remscheid',
        'Reutlingen',
        'Rheine',
        'Rüsselsheim',
        'Rosenheim',
        'Rostock',
        'Saarbrücken',
        'Sankt Augustin',
        'Salzgitter',
        'Schwäbisch Gmünd',
        'Schweinfurt',
        'Schwerin',
        'Siegen',
        'Sindelfingen',
        'Solingen',
        'Stoccarda',
        'Stolberg (Rhld.)',
        'Stralsund',
        'Treviri',
        'Troisdorf',
        'Tubinga',
        'Ulma',
        'Unna',
        'Velbert',
        'Viersen',
        'Villingen-Schwenningen',
        'Waiblingen',
        'Weimar',
        'Wesel',
        'Wetzlar',
        'Wiesbaden',
        'Wilhelmshaven',
        'Willich',
        'Witten',
        'Wolfenbüttel',
        'Wolfsburg',
        'Worms',
        'Wuppertal',
        'Würzburg',
        'Zwickau'
  		);
			$this->provinces = $provinces;
		}

		public function getProvinces(){
			return $this->provinces;
		}

	}
?>
